# Generated by Django 5.1.3 on 2024-11-21 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosEsteticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, verbose_name='ID')),
                ('NombreServicio', models.CharField(default='1', max_length=100)),
                ('Descripcion', models.CharField(default='1', max_length=100)),
                ('Duracion', models.CharField(default='1', max_length=50)),
                ('Precio', models.CharField(default='10', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoCorporal',
            fields=[
                ('serviciosesteticos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, to='CrudServiciosEsteticos.serviciosesteticos')),
                ('ZonaTratada', models.CharField(max_length=100)),
                ('TipoProducto', models.CharField(max_length=100)),
            ],
            bases=('CrudServiciosEsteticos.serviciosesteticos',),
        ),
        migrations.CreateModel(
            name='TratamientoFacial',
            fields=[
                ('serviciosesteticos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, to='CrudServiciosEsteticos.serviciosesteticos')),
                ('TipoTratamiento', models.CharField(max_length=100)),
                ('tipoPiel', models.CharField(max_length=100)),
            ],
            bases=('CrudServiciosEsteticos.serviciosesteticos',),
        ),
    ]
